name: 🐛 Bug Report
description: Report a bug in the RxTrace platform
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important: This is for RxTrace Platform Issues Only
        
        This repository is for the **RxTrace India pharmaceutical traceability platform**.
        
        **NOT for:**
        - GitHub Copilot issues → [GitHub Support](https://support.github.com/)
        - GitHub billing → [Billing Settings](https://github.com/settings/billing)
        - VS Code issues → [VS Code Repository](https://github.com/microsoft/vscode)
        
        ---

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm this issue is related to RxTrace platform
      options:
        - label: This issue is about the RxTrace pharmaceutical traceability platform (not GitHub Copilot, billing, or other GitHub services)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I try to generate labels, I get an error...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Labels should be generated and downloaded...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Error message appears or nothing happens...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the platform is affected?
      options:
        - Authentication (Sign in/Sign up)
        - Label Generation (Manual)
        - Label Generation (CSV Upload)
        - Barcode/QR Code Display
        - Product Verification
        - Dashboard
        - API
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - Browser: [e.g., Chrome 120]
        - OS: [e.g., Windows 11, macOS 14]
        - Device: [e.g., Desktop, Mobile]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This started happening after...
